const ticketsData = [
    {
        id: 1,
        day: 'WED',
        date: '30/11/2022',
        imageNameMain: '<img src="Screenshot_20221126-212130_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "testJpg.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    }, {
        id: 1,
        day: 'SAT',
        date: '26/11/2022',
        imageNameMain: '<img src="Screenshot_20221126-211102_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "testJpg.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 1,
        day: 'WED',
        date: '23/11/2022',
        imageNameMain: '<img src="Screenshot_20221123-160449_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221126-212012_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "testJpg.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 1,
        day: 'SAT',
        date: '19/11/2022',
        imageNameMain: '<img src="Screenshot_20221119-204257_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221117-124811_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221120-173021_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221120-173012_The National Lottery.jpg" alt="">',
        src: "testJpg.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '16/11/2022',
        imageNameMain: '<img src="Screenshot_20221117-124746_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221117-124802_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221117-124739_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221117-124757_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '12/11/2022',
        imageNameMain: '',
        imageNameExtra: '<img src="Screenshot_20221117-124627_The National Lottery.jpg" alt="">',
        imageNameMainResult: '',
        imageNameExtraResult: '<img src="Screenshot_20221117-124635_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 16/11)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '9/11/2022',
        imageNameMain: '<img src="Screenshot_20221117-124702_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221117-124709_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '5/11/2022',
        imageNameMain: '<img src="Screenshot_20221104-151040_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221104-151012_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221117-124533_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221117-124604_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'EURO-<BR>MILLIONS<br><br>FRI',
        date: '4/11/2022<br>(instead of ?/?)',
        imageNameMain: '<img src="Screenshot_20221104-151105_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '2/11/2022',
        imageNameMain: '<img src="Screenshot_20221102-162532_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221102-162449_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221104-211302_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221103-104026_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED<br>2/11/2022',
        date: '(instead of 22/10)',
        imageNameMain: '<img src="Screenshot_20221104-210108_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221103-104111_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '29/10/2022',
        imageNameMain: '<img src="Screenshot_20221029-222813_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221029-222737_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221030-001536_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221030-001508_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT<br>29/10/2022',
        date: '(instead of 15/10)',
        imageNameMain: '<img src="Screenshot_20221029-222844_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221030-001601_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '26/10/2022',
        imageNameMain: '<img src="Screenshot_20221026-190920_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221029-222607_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED<br>26/10/2022',
        date: '(instead of 12/10)',
        imageNameMain: '<img src="Screenshot_20221026-191019_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221029-222658_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '22/10/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 2/11)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '19/10/2022',
        imageNameMain: '<img src="Screenshot_20221018-091932_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221030-001435_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'EURO-<BR>MILLIONS<br><br>TUE',
        date: '18/10/2022<br>(instead of 5/10)',
        imageNameMain: '<img src="Screenshot_20221018-092025_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221029-230813_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '15/10/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 29/10)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '12/10/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 26/10)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '8/10/2022',
        imageNameMain: '<img src="Screenshot_20221007-195058_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221009-163756_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'EURO-<BR>MILLIONS<br><br>FRI',
        date: '7/10/2022<br>(instead of 14/9)',
        imageNameMain: '<img src="Screenshot_20221007-195127_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221008-011954_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '5/10/2022',
        imageNameMain: '',
        imageNameExtra: '<img src="Screenshot_20221007-194934_The National Lottery.jpg" alt="">',
        imageNameMainResult: '',
        imageNameExtraResult: '<img src="Screenshot_20221007-194959_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 18/10)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '1/10/2022',
        imageNameMain: '<img src="Screenshot_20220930-171136_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20220929-152059_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221007-193924_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221007-194104_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '28/9/2022',
        imageNameMain: '<img src="Screenshot_20220928-210257_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220929-152131_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '24/9/2022',
        imageNameMain: '<img src="Screenshot_20220926-164628_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20220926-164036_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20220926-164729_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20220926-164404_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '21/9/2022',
        imageNameMain: '<img src="Screenshot_20220926-163544_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220926-163910_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '17/9/2022',
        imageNameMain: '<img src="Screenshot_20220926-162553_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220926-162738_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '14/9/2022',
        imageNameMain: '',
        imageNameExtra: '<img src="Screenshot_20220926-162326_The National Lottery.jpg" alt="">',
        imageNameMainResult: '',
        imageNameExtraResult: '<img src="Screenshot_20220926-162020_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<span class="forgot">',
        secondElement: 'FORGOT!<br>(see 7/10)',
        thirdElement: '</span>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '10/9/2022',
        imageNameMain: '<img src="Screenshot_20220926-161244_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220926-161630_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '7/9/2022',
        imageNameMain: '<img src="Screenshot_20220907-171120_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220926-160655_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '3/9/2022',
        imageNameMain: '<img src="Screenshot_20220904-094721_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220904-094746_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '31/8/2022',
        imageNameMain: '<img src="Screenshot_20220829-221914_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220904-094649_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '27/8/2022',
        imageNameMain: '<img src="Screenshot_20220827-180502_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220829-221936_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '24/8/2022',
        imageNameMain: '<img src="Screenshot_20220824-151515_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220825-001826_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '20/8/2022',
        imageNameMain: '<img src="Screenshot_20220926-172200_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20220926-172053_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20220821-141931_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20220821-141942_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '17/8/2022',
        imageNameMain: '<img src="Screenshot_20220817-211238_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20220926-172700_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '13/8/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '10/8/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '6/8/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '3/8/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '30/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '27/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '23/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '20/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '16/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '13/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '9/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '6/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '2/7/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '29/6/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '25/6/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '22/6/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '18/6/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '15/6/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '11/6/2022',
        imageNameMain: '<img src="Screenshot_20221121-181927_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221121-181921_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '8/6/2022',
        imageNameMain: '<img src="Screenshot_20221121-181910_The National Lottery.jpg" alt="">',
        imageNameExtra: '<img src="Screenshot_20221121-181848_The National Lottery.jpg" alt="">',
        imageNameMainResult: '<img src="Screenshot_20221121-181904_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '<img src="Screenshot_20221121-181842_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '4/6/2022',
        imageNameMain: '<img src="Screenshot_20221121-181829_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221121-181823_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '1/6/2022',
        imageNameMain: '<img src="Screenshot_20221121-181811_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221121-181806_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'EURO-<BR>MILLIONS<br><br>TUE',
        date: '31/5/2022<br>(instead of ?/?)',
        imageNameMain: '<img src="Screenshot_20221121-181752_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '<img src="Screenshot_20221121-181746_The National Lottery.jpg" alt="">',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '28/5/2022',
        imageNameMain: '',
        imageNameExtra: '<img src="Screenshot_20221121-181733_The National Lottery.jpg" alt="">',
        imageNameMainResult: '',
        imageNameExtraResult: '<img src="Screenshot_20221121-181728_The National Lottery.jpg" alt="">',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '25/5/2022',
        imageNameMain: '<img src="Screenshot_20221121-181712_The National Lottery.jpg" alt="">',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'SAT',
        date: '21/5/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    },
    {
        id: 2,
        day: 'WED',
        date: '18/5/2022',
        imageNameMain: '',
        imageNameExtra: '',
        imageNameMainResult: '',
        imageNameExtraResult: '',
        src: "Screenshot_20221117-124746_The National Lottery.jpg",
        firstElement: '<a class="thumb" href="#">',
        secondElement: '<span class="imgLarge">',
        thirdElement: '</span></a>',
        fourthElement: '<a class="thumb" href="#">',
        fifthElement: '<span class="imgLarge">',
        sixthElement: '</span></a>',
        seventhElement: '<a class="thumb" href="#">',
        eighthElement: '<span class="imgLarge">',
        ninthElement: '</span></a>',
        tenthElement: '<a class="thumb" href="#">',
        eleventhElement: '<span class="imgLarge">',
        twelfthElement: '</span></a>'
    }
]
